apiVersion: v1
kind: Service
metadata:
  name: subscribers management
  labels:
    app: subscribers management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: subscribers management