---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: author management
  labels:
    app: author management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author management
  template:
    metadata:
      labels:
        app: author management
    spec:
      containers:
        - name: author management
          image: username/author management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscribers management
  labels:
    app: subscribers management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscribers management
  template:
    metadata:
      labels:
        app: subscribers management
    spec:
      containers:
        - name: subscribers management
          image: username/subscribers management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
  labels:
    app: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        - name: service
          image: username/service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: username/admin:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 대시보드
  labels:
    app: 대시보드
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 대시보드
  template:
    metadata:
      labels:
        app: 대시보드
    spec:
      containers:
        - name: 대시보드
          image: username/대시보드:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: author management
  labels:
    app: author management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: author management


---


apiVersion: v1
kind: Service
metadata:
  name: subscribers management
  labels:
    app: subscribers management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: subscribers management


---


apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: service


---


apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    app: admin
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: admin


---


apiVersion: v1
kind: Service
metadata:
  name: 대시보드
  labels:
    app: 대시보드
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 대시보드

